#!/bin/bash
#	script 	- Showing the conditional blocks
#
#	Copyright (C) 2022-04-17	Payam M
#
#	script No arguments are requirements.	

if (( 1 == 1 ))
then 
	echo "1 is 1. Duh!"
fi

if (( 1 == 1 ))
then echo "1 is 1. Duh!!"
fi

if (( 1 == 1 )); then
	echo "1 is 1. Duh!"
fi

if (( 1 == 1 )); then echo "1 is 1. Duh!"; fi

(( 1 == 1 )) && echo "1 is 1. Duh!"

a=1; b=1
[ $a == $b ] && echo "a and b are equal"
